[env]
TERM = "alacritty"

[window]
dimensions = { columns = 100, lines = 25 }
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = 'Both'

[font]
normal = { family = "SpaceMono Nerd Font", style = "Regular" }
bold = { family = "SpaceMono Nerd Font", style = "Bold" }
italic = { family = "SpaceMono Nerd Font", style = "Italic" }
bold_italic = { family = "SpaceMono Nerd Font", style = "Bold Italic" }
size = 20
# builtin_box_drawing = false

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" }
]

[general]
import = [
  "~/.config/catppuccin/alacritty/catppuccin-mocha.toml"
]

