# quick source tmux config file
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# change default prefix
unbind C-a
set -g prefix C-a
bind C-a send-prefix

# mouse usage
set -g mouse on

# increase history
set -g history-limit 10000

# jump to marked pane
bind \` switch-client -t '{marked}'

# number windows and panes
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# more intuitive split commands
unbind %
unbind \"
unbind h
bind h split-window -hc "#{pane_current_path}"
unbind v
bind v split-window -vc "#{pane_current_path}"

# swapping windows
unbind "<"
bind -r "<" swap-window -d -t -1
unbind ">"
bind -r ">" swap-window -d -t +1

# keeping current path
unbind c
bind c new-window -c "#{pane_current_path}"

# toggling windows and sessions
unbind a
bind a last-window
unbind C-a
bind C-a switch-client -l

# resizing
unbind C-j
bind -r C-j resize-pane -D 5
unbind C-k
bind -r C-k resize-pane -U 5
unbind C-h
bind -r C-h resize-pane -L 5
unbind C-l
bind -r C-l resize-pane -R 5

# breaking and joining panes
unbind j
bind j choose-window 'join-pane -h -s"%%"'
unbind J
bind J choose-window 'join-pane -v -s "%%"'

# catppuccin theme
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# embedding vim statusline in tmux statusline
set -g focus-events on
# set -g status-style bg=default
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g status-left-length 90
set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
set -g status-right-length 90
set -g status-justify centre

# tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'

run '~/.config/tmux/tpm/tpm'

